site_name: 'cache4k'
site_description: "In-memory Cache for Kotlin Multiplatform"
site_author: 'Yang Chen'
site_url: 'https://reactivecircus.github.io/cache4k'
remote_branch: gh-pages

repo_name: 'cache4k'
repo_url: 'https://github.com/ReactiveCircus/cache4k'

copyright: 'Copyright &copy; 2021 Yang Chen'

theme:
  name: 'material'
  language: 'en'
  favicon: 'images/reactive_circus_logo.png'
  logo: 'images/reactive_circus_logo.png'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Fira Sans'
    code: 'Fira Code'
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ReactiveCircus/cache4k'

nav:
  - 'Overview': index.md
  - 'Change Log': changelog.md
  - 'API Docs': api/index.html" target="_blank

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: True
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

plugins:
  - search
  - minify:
      minify_html: true
